#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# VulnClaw first-run setup: LLM credentials, Chrome DevTools MCP (for Cloudflare
# / real-browser recon), optional Burp MCP, then doctor verification.
#
# Values land in:
#   - ~/.vulnclaw/config.yaml  via `vulnclaw config …` (primary runtime config)
#   - ENV_FILE (defaults to ~/.vulnclaw/wizard.env) for re-run memory only
#
# Preferred in a live session: type  /wizard  inside  vulnclaw
# (native Python UI). This bash script is the offline / portable twin.

TOTAL_STAGES=7
TOTAL_MINUTES=20
ENV_FILE="${ENV_FILE:-${HOME}/.vulnclaw/wizard.env}"
mkdir -p "$(dirname "$ENV_FILE")"
mkdir -p "${HOME}/.vulnclaw"

_vc() {
  if command -v vulnclaw >/dev/null 2>&1; then
    vulnclaw "$@"
    return
  fi
  if command -v python >/dev/null 2>&1 && python -c "import vulnclaw" 2>/dev/null; then
    python -m vulnclaw "$@"
    return
  fi
  if command -v python3 >/dev/null 2>&1 && python3 -c "import vulnclaw" 2>/dev/null; then
    python3 -m vulnclaw "$@"
    return
  fi
  return 127
}

_have() { command -v "$1" >/dev/null 2>&1; }

_detect_chrome() {
  local c
  for c in \
    "/c/Program Files/Google/Chrome/Application/chrome.exe" \
    "/mnt/c/Program Files/Google/Chrome/Application/chrome.exe" \
    "/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" \
    "/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" \
    "C:/Program Files/Google/Chrome/Application/chrome.exe" \
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" \
    "$(command -v google-chrome 2>/dev/null || true)" \
    "$(command -v google-chrome-stable 2>/dev/null || true)" \
    "$(command -v chromium 2>/dev/null || true)" \
    "$(command -v chromium-browser 2>/dev/null || true)"
  do
    if [[ -n "$c" && -x "$c" ]]; then
      printf '%s' "$c"
      return 0
    fi
    if [[ -n "$c" && -f "$c" ]]; then
      printf '%s' "$c"
      return 0
    fi
  done
  return 1
}

_port_open() {
  local host="${1:-127.0.0.1}" port="${2:-9222}"
  if _have curl; then
    curl -fsS --max-time 2 "http://${host}:${port}/json/version" >/dev/null 2>&1
    return $?
  fi
  if _have python3; then
    python3 - "$host" "$port" <<'PY' 2>/dev/null
import socket, sys
s = socket.socket()
s.settimeout(2)
try:
    s.connect((sys.argv[1], int(sys.argv[2])))
except OSError:
    sys.exit(1)
finally:
    s.close()
PY
    return $?
  fi
  if _have python; then
    python - "$host" "$port" <<'PY' 2>/dev/null
import socket, sys
s = socket.socket()
s.settimeout(2)
try:
    s.connect((sys.argv[1], int(sys.argv[2])))
except OSError:
    sys.exit(1)
finally:
    s.close()
PY
    return $?
  fi
  return 1
}

_run_py() {
  if command -v python >/dev/null 2>&1; then
    python "$@"
  elif command -v python3 >/dev/null 2>&1; then
    python3 "$@"
  else
    return 127
  fi
}

_enable_chrome_devtools_mcp() {
  local browser_url="${1:-http://127.0.0.1:9222}"
  # Nested list args are awkward via `config set`; patch YAML with Python.
  _run_py - "$browser_url" <<'PY'
import sys
from pathlib import Path

try:
    from vulnclaw.config.settings import load_config, save_config
except Exception as exc:  # pragma: no cover
    print(f"[!] could not import vulnclaw config: {exc}", file=sys.stderr)
    sys.exit(1)

browser_url = sys.argv[1]
config = load_config()
servers = config.mcp.servers
# Ensure chrome-devtools server exists with correct transport.
if "chrome-devtools" not in servers:
    from vulnclaw.config.schema import MCPServerConfig, MCPTransportConfig
    servers["chrome-devtools"] = MCPServerConfig(
        name="chrome-devtools",
        enabled=True,
        priority=0,
        description="Browser automation for Web app pentest",
        transport=MCPTransportConfig(
            type="stdio",
            command="npx",
            args=["-y", "chrome-devtools-mcp@latest", f"--browser-url={browser_url}"],
        ),
    )
else:
    srv = servers["chrome-devtools"]
    srv.enabled = True
    srv.transport.type = "stdio"
    srv.transport.command = "npx"
    srv.transport.args = [
        "-y",
        "chrome-devtools-mcp@latest",
        f"--browser-url={browser_url}",
    ]
save_config(config)
print(f"enabled chrome-devtools → {browser_url}")
print(f"config: {Path.home() / '.vulnclaw' / 'config.yaml'}")
PY
}

_enable_burp_mcp() {
  local sse_url="${1:-http://127.0.0.1:9876}"
  _run_py - "$sse_url" <<'PY'
import sys
try:
    from vulnclaw.config.settings import load_config, save_config
except Exception as exc:
    print(f"[!] could not import vulnclaw config: {exc}", file=sys.stderr)
    sys.exit(1)

sse_url = sys.argv[1]
config = load_config()
servers = config.mcp.servers
if "burp" not in servers:
    from vulnclaw.config.schema import MCPServerConfig, MCPTransportConfig
    servers["burp"] = MCPServerConfig(
        name="burp",
        enabled=True,
        priority=0,
        description="Burp Suite proxy integration for HTTP interception via SSE",
        transport=MCPTransportConfig(type="sse", url=sse_url),
    )
else:
    srv = servers["burp"]
    srv.enabled = True
    srv.transport.type = "sse"
    srv.transport.url = sse_url
save_config(config)
print(f"enabled burp MCP → {sse_url}")
PY
}

banner "VulnClaw first-run setup"

# ── 1. Prerequisites ──────────────────────────────────────────────────────
stage "Prerequisites" 2
say "Checking tools VulnClaw needs for LLM + browser + recon."
note "python / python3, node + npx, Chrome, and the vulnclaw package."

if _have python3 || _have python; then
  note "✓ Python: $(python3 --version 2>/dev/null || python --version 2>/dev/null || echo ok)"
else
  warn "Python 3.11+ not found on PATH."
  SKIPPED+=("Install Python 3.11+ and re-run")
fi

if _have node; then
  note "✓ Node.js: $(node --version 2>/dev/null || true)"
else
  warn "Node.js not found — chrome-devtools MCP uses npx."
  open_url "https://nodejs.org/en/download"
  step "Install Node.js LTS (v20+), then return here."
  pause "Press Enter after Node is installed"
fi

if _have npx; then
  note "✓ npx available"
else
  warn "npx missing (comes with Node LTS)."
  SKIPPED+=("Install Node.js LTS so npx works")
fi

if _have nmap; then
  note "✓ nmap: $(nmap --version 2>/dev/null | head -n1 || true)"
else
  warn "nmap not found — port scans will be limited."
  note "Windows: install Nmap from https://nmap.org/download.html and add it to PATH."
  open_url "https://nmap.org/download.html"
  if ! confirm "Skip nmap for now and continue?"; then
    pause "Install nmap, then press Enter"
  else
    SKIPPED+=("Install nmap for better recon")
  fi
fi

if _vc --help >/dev/null 2>&1 || _vc doctor >/dev/null 2>&1 || command -v vulnclaw >/dev/null 2>&1; then
  note "✓ vulnclaw CLI reachable"
else
  warn "vulnclaw not on PATH. From this repo: pip install -e ."
  step "In a shell:  pip install -e .   (or: pip install vulnclaw)"
  pause "Press Enter once vulnclaw is importable"
fi

CHROME_PATH="$(_detect_chrome || true)"
if [[ -n "${CHROME_PATH:-}" ]]; then
  note "✓ Chrome found: $CHROME_PATH"
  write_env CHROME_PATH "$CHROME_PATH"
else
  warn "Chrome/Chromium not auto-detected."
  ask CHROME_PATH "Full path to chrome.exe / Google Chrome (or leave blank to skip browser MCP later):"
  if [[ -n "${CHROME_PATH}" ]]; then
    write_env CHROME_PATH "$CHROME_PATH"
  else
    SKIPPED+=("Install Google Chrome for chrome-devtools MCP")
  fi
fi
pause "Prereqs noted — continue?"

# ── 2. LLM provider ───────────────────────────────────────────────────────
stage "LLM provider" 3
say "VulnClaw needs an OpenAI-compatible model with tool/function calling."
note "Interactive shortcut: vulnclaw config provider <name>  fills base_url + default model."
say "Common providers: openai, anthropic, deepseek, minimax, zhipu, moonshot, qwen, ollama, siliconflow"
ask LLM_PROVIDER "Provider name:"
if [[ -z "${LLM_PROVIDER}" ]]; then
  warn "No provider entered — skipping LLM config for this run."
  SKIPPED+=("Set LLM later: vulnclaw config provider <name> && vulnclaw config set llm.api_key …")
else
  write_env LLM_PROVIDER "$LLM_PROVIDER"
  if _vc config provider "$LLM_PROVIDER" >/dev/null 2>&1; then
    note "✓ applied provider preset: $LLM_PROVIDER"
  else
    warn "vulnclaw config provider failed — you can set base_url/model manually next."
    ask LLM_BASE_URL "API base URL (e.g. https://api.openai.com/v1):"
    ask LLM_MODEL "Model name (e.g. gpt-4o):"
    [[ -n "${LLM_BASE_URL:-}" ]] && _vc config set llm.base_url "$LLM_BASE_URL" || true
    [[ -n "${LLM_MODEL:-}" ]] && _vc config set llm.model "$LLM_MODEL" || true
    [[ -n "${LLM_BASE_URL:-}" ]] && write_env LLM_BASE_URL "$LLM_BASE_URL"
    [[ -n "${LLM_MODEL:-}" ]] && write_env LLM_MODEL "$LLM_MODEL"
  fi
  if [[ "${LLM_PROVIDER}" == "ollama" ]]; then
    say "Ollama needs no real API key; a placeholder is fine."
    _vc config set llm.api_key ollama >/dev/null 2>&1 || true
    write_env VULNCLAW_LLM_API_KEY "ollama"
  else
    if confirm "Open the provider dashboard / console to create an API key?"; then
      case "$LLM_PROVIDER" in
        openai) open_url "https://platform.openai.com/api-keys" ;;
        anthropic) open_url "https://console.anthropic.com/settings/keys" ;;
        deepseek) open_url "https://platform.deepseek.com/api_keys" ;;
        minimax) open_url "https://platform.minimaxi.com/" ;;
        zhipu) open_url "https://open.bigmodel.cn/usercenter/apikeys" ;;
        moonshot) open_url "https://platform.moonshot.cn/console/api-keys" ;;
        qwen) open_url "https://dashscope.console.aliyun.com/apiKey" ;;
        siliconflow) open_url "https://cloud.siliconflow.cn/account/ak" ;;
        *) note "Open your provider console and create an API key." ;;
      esac
    fi
    step "Copy the API key from the provider console."
    ask_secret VULNCLAW_LLM_API_KEY "Paste the API key (hidden):"
    if [[ -n "${VULNCLAW_LLM_API_KEY}" ]]; then
      write_env VULNCLAW_LLM_API_KEY "$VULNCLAW_LLM_API_KEY"
      if _vc config set llm.api_key "$VULNCLAW_LLM_API_KEY" >/dev/null 2>&1; then
        note "✓ wrote llm.api_key into ~/.vulnclaw/config.yaml"
      else
        warn "Could not write via vulnclaw; key stays in $ENV_FILE only. Export VULNCLAW_LLM_API_KEY before launch."
      fi
    else
      warn "Empty API key — agent will not run until you set one."
      SKIPPED+=("vulnclaw config set llm.api_key <key>")
    fi
  fi
  if confirm "Override the default model name for this provider?"; then
    ask LLM_MODEL "Model name:"
    if [[ -n "${LLM_MODEL}" ]]; then
      write_env LLM_MODEL "$LLM_MODEL"
      _vc config set llm.model "$LLM_MODEL" >/dev/null 2>&1 || true
    fi
  fi
fi

# ── 3. Language ───────────────────────────────────────────────────────────
stage "UI language" 1
say "VulnClaw UI language: en (English) or zh (Chinese)."
ask VC_LANGUAGE "Language code [en/zh]:"
if [[ -z "${VC_LANGUAGE}" ]]; then
  VC_LANGUAGE="en"
fi
case "$VC_LANGUAGE" in
  en|zh)
    write_env VC_LANGUAGE "$VC_LANGUAGE"
    _vc config set session.language "$VC_LANGUAGE" >/dev/null 2>&1 || true
    note "✓ session.language=$VC_LANGUAGE (REPL: /language $VC_LANGUAGE)"
    ;;
  *)
    warn "Unrecognized language '$VC_LANGUAGE' — leaving default."
    ;;
esac

# ── 4. Chrome remote debugging ────────────────────────────────────────────
stage "Chrome remote debugging" 4
say "Bare HTTP fetch gets Cloudflare 403s on many bounty targets."
say "A real Chrome with remote debugging lets chrome-devtools MCP browse as you do."
note "Use a SEPARATE user-data-dir so this profile does not lock your daily Chrome."

CHROME_DEBUG_PORT="${CHROME_DEBUG_PORT:-9222}"
ask CHROME_DEBUG_PORT "Remote debugging port [default 9222]:"
[[ -z "${CHROME_DEBUG_PORT}" ]] && CHROME_DEBUG_PORT=9222
write_env CHROME_DEBUG_PORT "$CHROME_DEBUG_PORT"

if [[ -z "${CHROME_PATH:-}" ]]; then
  CHROME_PATH="$(_existing CHROME_PATH || true)"
fi
if [[ -z "${CHROME_PATH:-}" ]]; then
  CHROME_PATH="$(_detect_chrome || true)"
fi
if [[ -z "${CHROME_PATH:-}" ]]; then
  ask CHROME_PATH "Chrome executable path:"
fi

# Profile directories (platform-aware defaults)
if [[ "$(uname -s 2>/dev/null || echo unknown)" == "Darwin" ]]; then
  DEFAULT_PROFILE="${HOME}/.vulnclaw/chrome-debug"
elif [[ -d /mnt/c/Users ]] || [[ "$(uname -o 2>/dev/null || true)" == "Msys" ]] || [[ "$(uname -o 2>/dev/null || true)" == "Cygwin" ]]; then
  DEFAULT_PROFILE="${HOME}/.vulnclaw/chrome-debug"
  # Prefer a Windows-native path if we're in Git Bash and HOME is under /c/Users
  if [[ "$HOME" == /c/Users/* ]] || [[ "$HOME" == /mnt/c/Users/* ]]; then
    DEFAULT_PROFILE="${HOME}/.vulnclaw/chrome-debug"
  fi
else
  DEFAULT_PROFILE="${HOME}/.vulnclaw/chrome-debug"
fi

ask CHROME_USER_DATA_DIR "Chrome user-data-dir for agent profile:"
if [[ -z "${CHROME_USER_DATA_DIR}" ]]; then
  CHROME_USER_DATA_DIR="$DEFAULT_PROFILE"
fi
write_env CHROME_USER_DATA_DIR "$CHROME_USER_DATA_DIR"
mkdir -p "$CHROME_USER_DATA_DIR" 2>/dev/null || true

if [[ -n "${CHROME_PATH}" ]]; then
  say "Start Chrome with remote debugging (leave it running):"
  note "  \"$CHROME_PATH\" --remote-debugging-port=${CHROME_DEBUG_PORT} --user-data-dir=\"${CHROME_USER_DATA_DIR}\""
  if confirm "Launch Chrome now from this wizard?"; then
    if [[ "$CHROME_PATH" == *.exe ]] || [[ "$CHROME_PATH" == /c/* ]] || [[ "$CHROME_PATH" == /mnt/c/* ]]; then
      # Windows path via Git Bash / WSL
      if _have cmd.exe; then
        cmd.exe /c start "" "$CHROME_PATH" --remote-debugging-port="${CHROME_DEBUG_PORT}" --user-data-dir="${CHROME_USER_DATA_DIR}" >/dev/null 2>&1 || \
          "$CHROME_PATH" --remote-debugging-port="${CHROME_DEBUG_PORT}" --user-data-dir="${CHROME_USER_DATA_DIR}" >/dev/null 2>&1 &
      else
        "$CHROME_PATH" --remote-debugging-port="${CHROME_DEBUG_PORT}" --user-data-dir="${CHROME_USER_DATA_DIR}" >/dev/null 2>&1 &
      fi
    else
      "$CHROME_PATH" --remote-debugging-port="${CHROME_DEBUG_PORT}" --user-data-dir="${CHROME_USER_DATA_DIR}" >/dev/null 2>&1 &
    fi
    sleep 2
  else
    step "Run the launch command above in another terminal, then return."
    pause "Press Enter once Chrome is running with remote debugging"
  fi
else
  warn "No Chrome path — skipping launch. Start Chrome yourself with --remote-debugging-port=${CHROME_DEBUG_PORT}"
  SKIPPED+=("Launch Chrome with remote debugging before browser tasks")
fi

if _port_open 127.0.0.1 "$CHROME_DEBUG_PORT"; then
  note "✓ DevTools endpoint reachable on port ${CHROME_DEBUG_PORT}"
else
  warn "Port ${CHROME_DEBUG_PORT} not answering yet."
  step "Confirm only one Chrome uses that profile, wait a few seconds, re-check."
  if ! confirm "Continue anyway (you can start Chrome later)?"; then
    pause "Start Chrome with debugging, then press Enter"
  fi
fi

step "In that Chrome window, manually pass any Cloudflare checks for targets you care about."
note "Cookies stay in ${CHROME_USER_DATA_DIR}; the agent reuses that session via MCP."
pause "Chrome ready?"

# ── 5. chrome-devtools MCP ────────────────────────────────────────────────
stage "chrome-devtools MCP" 3
say "Enable VulnClaw's chrome-devtools MCP server and point it at the debug port."
BROWSER_URL="http://127.0.0.1:${CHROME_DEBUG_PORT}"
write_env BROWSER_URL "$BROWSER_URL"

if ! confirm "Enable chrome-devtools MCP now?"; then
  SKIPPED+=("Enable chrome-devtools MCP: re-run wizard or config by hand")
else
  if _enable_chrome_devtools_mcp "$BROWSER_URL"; then
    note "✓ mcp.servers.chrome-devtools enabled with --browser-url=${BROWSER_URL}"
  else
    warn "Auto-patch failed — applying fallback CLI flags."
    _vc config set mcp.servers.chrome-devtools.enabled true >/dev/null 2>&1 || true
    _vc config set mcp.servers.chrome-devtools.transport.command npx >/dev/null 2>&1 || true
    _vc config set mcp.servers.chrome-devtools.transport.args \
      "-y,chrome-devtools-mcp@latest,--browser-url=${BROWSER_URL}" >/dev/null 2>&1 || true
    SKIPPED+=("Verify ~/.vulnclaw/config.yaml chrome-devtools.transport.args includes --browser-url=${BROWSER_URL}")
  fi
  note "After config changes, restart VulnClaw so MCP reloads."
  note "Next launch banner should list chrome-devtools (not only 2 services)."
fi
pause "Continue?"

# ── 6. Burp Suite MCP (optional) ──────────────────────────────────────────
stage "Burp Suite MCP (optional)" 5
say "Burp MCP is optional. Needs Burp Suite Professional + Java 11+ + MCP extension."
if ! confirm "Set up Burp MCP now?"; then
  note "Skipping Burp — you can re-run this wizard later."
  SKIPPED+=("Optional: Burp Suite MCP (see README_EN.md Burp section)")
else
  open_url "https://github.com/PortSwigger/mcp-server"
  step "Clone the official server:  git clone https://github.com/PortSwigger/mcp-server.git burp-mcp"
  step "Build:  cd burp-mcp && ./gradlew embedProxyJar   (Windows: gradlew.bat embedProxyJar)"
  step "In Burp: Extensions → Add → Type Java → select the built burp-mcp-all.jar"
  step "In Burp: open the MCP tab and enable the server (default SSE http://127.0.0.1:9876)"
  pause "Press Enter after Burp MCP is enabled in Burp"
  ask BURP_SSE_URL "Burp MCP SSE URL:"
  [[ -z "${BURP_SSE_URL}" ]] && BURP_SSE_URL="http://127.0.0.1:9876"
  write_env BURP_SSE_URL "$BURP_SSE_URL"
  if _enable_burp_mcp "$BURP_SSE_URL"; then
    note "✓ mcp.servers.burp enabled → $BURP_SSE_URL"
  else
    _vc config set mcp.servers.burp.enabled true >/dev/null 2>&1 || true
    _vc config set mcp.servers.burp.transport.url "$BURP_SSE_URL" >/dev/null 2>&1 || true
    SKIPPED+=("Verify burp MCP in ~/.vulnclaw/config.yaml")
  fi
  note "Keep Burp running when you want traffic tools available to VulnClaw."
fi

# ── 7. Verify ─────────────────────────────────────────────────────────────
stage "Verify" 2
say "Running environment checks."
if _vc doctor 2>&1; then
  note "✓ vulnclaw doctor finished (review MCP Services section above)."
else
  warn "vulnclaw doctor failed or is unavailable — start the REPL and check the MCP banner."
fi

say "Manual smoke checklist:"
step "1. Start Chrome with remote debugging (stage 4 command) if not already running."
step "2. From the repo shell:  vulnclaw"
step "3. Banner should mention chrome-devtools (and burp if enabled)."
step "4. Try: /hackerone https://hackerone.com/<handle>/policy_scopes"
step "5. When app 403s, prefer browser MCP tools over bare fetch."

write_env WIZARD_COMPLETED_AT "$(date -Iseconds 2>/dev/null || date)"
finish

printf '%sNext:%s\n' "$BOLD" "$RESET"
printf '  1. Start debug Chrome if needed (command stored in %s).\n' "$ENV_FILE"
printf '  2. Run:  vulnclaw\n'
printf '  3. Re-run this wizard any time:  bash scripts/vulnclaw-setup-wizard.sh\n\n'
